models:
  tinyllama:
    name: "TinyLlama-1.1B-Chat-v1.0"
    path: "TinyLlama/TinyLlama-1.1B-Chat-v1.0"
    energy_per_token: 0.001
    max_length: 512
    carbon_threshold: 200
    use_gpu: false
    description: "Lightweight model for simple tasks during high carbon intensity"

  gpt2:
    name: "GPT-2"
    path: "gpt2"
    energy_per_token: 0.01
    max_length: 1024
    carbon_threshold: 100
    use_gpu: true
    description: "Medium-sized model for moderate complexity tasks"

  gpt4:
    name: "GPT-4"
    path: "gpt-4"
    energy_per_token: 0.1
    max_length: 4096
    carbon_threshold: 50
    use_gpu: true
    description: "Large model for complex tasks during low carbon intensity"

defaults:
  fallback_model: "tinyllama"
  max_retries: 3
  timeout: 30 